// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ_0MxMEzaXCRcysvqM262E3L10lfCJkI',
    appId: '1:234716053312:web:6a21a7228b7e2e03e844a5',
    messagingSenderId: '234716053312',
    projectId: 'spaxey-stg',
    authDomain: 'spaxey-stg.firebaseapp.com',
    storageBucket: 'spaxey-stg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZsIycNzRX0VNgEKcPFpXh0rw2J9e4hI',
    appId: '1:234716053312:android:fc34d7948a0986b4e844a5',
    messagingSenderId: '234716053312',
    projectId: 'spaxey-stg',
    storageBucket: 'spaxey-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBraPoNBDYuLx0v28W9ov8jPrXRn30z_YQ',
    appId: '1:234716053312:ios:a48c62d37917b31ae844a5',
    messagingSenderId: '234716053312',
    projectId: 'spaxey-stg',
    storageBucket: 'spaxey-stg.firebasestorage.app',
    iosClientId: '234716053312-9jr3j807nj8ifme40hvm42l9cc0hg43l.apps.googleusercontent.com',
    iosBundleId: 'com.gamley1.spaxey.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBraPoNBDYuLx0v28W9ov8jPrXRn30z_YQ',
    appId: '1:234716053312:ios:a883586b0f269d7ae844a5',
    messagingSenderId: '234716053312',
    projectId: 'spaxey-stg',
    storageBucket: 'spaxey-stg.firebasestorage.app',
    iosClientId: '234716053312-6t19v6oqif8c79rn5rdo09dsje9mhg3r.apps.googleusercontent.com',
    iosBundleId: 'com.gambley1.spaxey.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ_0MxMEzaXCRcysvqM262E3L10lfCJkI',
    appId: '1:234716053312:web:b16665af42ad7e00e844a5',
    messagingSenderId: '234716053312',
    projectId: 'spaxey-stg',
    authDomain: 'spaxey-stg.firebaseapp.com',
    storageBucket: 'spaxey-stg.firebasestorage.app',
  );
}
