// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Fn4t9zIeIJuwTYXfMYZpgzGv1KtZRF0',
    appId: '1:427124386853:web:0190942cd5ba0c669c63cc',
    messagingSenderId: '427124386853',
    projectId: 'spaxey-prod-8a663',
    authDomain: 'spaxey-prod-8a663.firebaseapp.com',
    storageBucket: 'spaxey-prod-8a663.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlWongG5kRFQBapkGkC_SMutvJww5tqBY',
    appId: '1:427124386853:android:9781e89b4e896fe79c63cc',
    messagingSenderId: '427124386853',
    projectId: 'spaxey-prod-8a663',
    storageBucket: 'spaxey-prod-8a663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJgmsawMIt4-cdC2n5gyWqV-bM_zqAMQ',
    appId: '1:427124386853:ios:5b97dc89556f802a9c63cc',
    messagingSenderId: '427124386853',
    projectId: 'spaxey-prod-8a663',
    storageBucket: 'spaxey-prod-8a663.firebasestorage.app',
    iosClientId: '427124386853-58naigcuddpihtu5rleriqof1q4puik6.apps.googleusercontent.com',
    iosBundleId: 'com.gamley1.spaxey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJgmsawMIt4-cdC2n5gyWqV-bM_zqAMQ',
    appId: '1:427124386853:ios:42f1bfe28b92caa79c63cc',
    messagingSenderId: '427124386853',
    projectId: 'spaxey-prod-8a663',
    storageBucket: 'spaxey-prod-8a663.firebasestorage.app',
    iosClientId: '427124386853-e0cbhosf40m1bb78nq7uimpu9earrikb.apps.googleusercontent.com',
    iosBundleId: 'com.gambley1.spaxey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Fn4t9zIeIJuwTYXfMYZpgzGv1KtZRF0',
    appId: '1:427124386853:web:96a3e1757f025dc89c63cc',
    messagingSenderId: '427124386853',
    projectId: 'spaxey-prod-8a663',
    authDomain: 'spaxey-prod-8a663.firebaseapp.com',
    storageBucket: 'spaxey-prod-8a663.firebasestorage.app',
  );

}
