// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTcroWKjstMYWcHICnRnBghDClQAyfB2s',
    appId: '1:1033256263772:web:8287dd919b20b6169e8699',
    messagingSenderId: '1033256263772',
    projectId: 'spaxey-dev',
    authDomain: 'spaxey-dev.firebaseapp.com',
    storageBucket: 'spaxey-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Kf3l3FQx67MYxBu1sVBoWuyejGaE2VU',
    appId: '1:1033256263772:android:8888782251998b989e8699',
    messagingSenderId: '1033256263772',
    projectId: 'spaxey-dev',
    storageBucket: 'spaxey-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZf2PkWQbdlseXd3nRqMegoQkMzKYR8rE',
    appId: '1:1033256263772:ios:ee092e0d7798c9e19e8699',
    messagingSenderId: '1033256263772',
    projectId: 'spaxey-dev',
    storageBucket: 'spaxey-dev.firebasestorage.app',
    iosClientId: '1033256263772-b1be8rm5i69e85jqk1ciive010fr69em.apps.googleusercontent.com',
    iosBundleId: 'com.gamley1.spaxey.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZf2PkWQbdlseXd3nRqMegoQkMzKYR8rE',
    appId: '1:1033256263772:ios:0fa200c13784e79f9e8699',
    messagingSenderId: '1033256263772',
    projectId: 'spaxey-dev',
    storageBucket: 'spaxey-dev.firebasestorage.app',
    iosClientId: '1033256263772-q4ctp7kgeq93q2fo4fj9is63lsuo5t28.apps.googleusercontent.com',
    iosBundleId: 'com.gambley1.spaxey.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTcroWKjstMYWcHICnRnBghDClQAyfB2s',
    appId: '1:1033256263772:web:7ad3cc7a1c31785c9e8699',
    messagingSenderId: '1033256263772',
    projectId: 'spaxey-dev',
    authDomain: 'spaxey-dev.firebaseapp.com',
    storageBucket: 'spaxey-dev.firebasestorage.app',
  );
}
