name: env
description: A repository that manages enviromental viariables.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  envied: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.7.0
  envied_generator: ^1.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
