name: powersync_repository
description: A package that manages connection to the PowerSync cloud service and database.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  env:
    path: ../env

  flutter:
    sdk: flutter

  path: ">=1.8.3 <2.0.0" # No newer major version yet

  path_provider: ^2.1.5       # Latest stable version :contentReference[oaicite:0]{index=0}
  powersync: ^1.2.2           # (Assuming no newer version; check manually if necessary)
  shared:
    path: ../shared

  sorted: ^2.1.0
  supabase_flutter: ^2.9.1    # Latest version released June 2025 :contentReference[oaicite:1]{index=1}

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2            # Still valid unless updated
  very_good_analysis: ^6.0.0  # Latest as far as available
